# This file was generated by GoReleaser. DO NOT EDIT.
class Devto < Formula
  desc "CLI tool to publish article to https://dev.to/"
  homepage "https://github.com/shihanng/devto"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/shihanng/devto/releases/download/v0.0.3/devto_darwin_amd64.tar.gz"
    sha256 "b0a5d70026111a69b4a3e808a88cf974977a96ffc16e59293d91f9f858d01207"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/shihanng/devto/releases/download/v0.0.3/devto_linux_amd64.tar.gz"
      sha256 "3f6ee66636040cd671ca3d8854a590f99ceeed44e9710435f24f1f79dd5d6e1e"
    end
  end

  def install
    bin.install Dir['devto']
  end

  test do
    system "#{bin}/devto"
  end
end
